#!/usr/bin/env php
<?php

require_once dirname(__FILE__) . '/vendor/autoload.php';

use \Intersect\Application;

$application = Application::instance();
$application->setBasePath(realpath(__DIR__));
$application->init();

$commandRunner = new \Intersect\Core\Command\CommandRunner($application);
$commandRunner->run($argv, $argc);